### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by halvardssm** [lucacasonato/deno-puppeteer#16]
Hi @lucacasonato ! 

I am trying to create a docker image where I use Deno with Oak and Puppeteer, but I am having some issues with Puppeteer. So far, this is my docker image, but I cannot seem to make it work. I have two main issues at the moment:

1: The install script does not seem to recognize that an existing installation exists
2: Puppeteer is not able to run the downloaded chromium

Here is my Dockerfile (assume that all the variables are set). Let me know if I can provide you with any other information!

```dockerfile
FROM hayd/alpine-deno:1.7.2

EXPOSE ${MICROSERVICE_PORT}

WORKDIR /app

# As provided by https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine
RUN apk add --no-cache \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont 


ENV PUPPETEER_EXECUTABLE_PATH=/deno-dir/deno_puppeteer/chromium/linux-818858/chrome-linux/chrome

ADD . .

RUN PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@${PUPPETEER_VERSION}/install.ts

RUN deno install -qAf --unstable https://deno.land/x/denon/denon.ts

RUN deno cache --unstable src/deps.ts

RUN deno cache --unstable src/mod.ts

USER deno

ENTRYPOINT [ "denon"]

CMD ["run","--unstable","-A","src/mod.ts" ]
```

This is the error that I am receiving when I try to use Puppeteer:

```sh
Error: Failed to launch the browser process!
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at waitForWSEndpoint (BrowserRunner.ts:174:9)
    at async BrowserRunner.setupConnection (BrowserRunner.ts:143:31)
    at async ChromeLauncher.launch (Launcher.ts:108:26)
    at async createPDF (pdf-handler.ts:4:19)
    at async routes.ts:14:19
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async Application.#handleRequest (application.ts:252:9)
```

**Comment by jupegarnica** [comment]
same here

**Comment by bennettdams** [comment]
Same goes for running with WSL 2.

**Comment by jsejcksn** [comment]
Source:
https://github.com/lucacasonato/deno-puppeteer/blob/aa7dc667a9c0d0e3cfe93ca2f7d5f8183cf0708c/src/deno/BrowserRunner.ts#L156-L183

Haven't tried to debug this yet, but here are some initial thoughts:

1. Is the "listening" message still being emitted to `stderr` and not `stdout`?
2. Is the regex still accurate?

**Comment by mt-u** [comment]
Hi @lucacasonato .
When I run deno and puppeteer on a Docker container, I get the same error message as @halvardssm.
So I recreated the Dockerfile according to the [trouble shooting link](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) shown in the error message.
Then I got another error.
`error: Uncaught (in promise) BadResource: Bad resource ID`
Does this help anything?

Dockerfile is
```Dockerfile
FROM debian:buster-20210511-slim

ENV DENO_VERSION=1.10.1
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    curl \
    ca-certificates \
    unzip \
# ↓ from puppeteer instruction https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
    wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
# ↑ from puppeteer instruction https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
    && curl -fsSL https://github.com/denoland/deno/releases/download/v${DENO_VERSION}/deno-x86_64-unknown-linux-gnu.zip \
    --output deno.zip \
    && unzip deno.zip \
    && rm deno.zip \
    && chmod 755 deno \
    && mv deno /usr/bin/deno \
    && apt-get -qq remove --purge -y \
    curl \
    ca-certificates \
    unzip \
    && apt-get -y -qq autoremove \
    && apt-get -qq clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd --uid 1993 --user-group deno \
 && mkdir /deno-dir/ \
 && chown deno:deno /deno-dir/

ENV DENO_DIR /deno-dir/

# https://deno.land/x/puppeteer@9.0.0#installation
RUN PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@9.0.0/install.ts

WORKDIR /root
ENTRYPOINT ["deno"]
CMD ["run", "https://deno.land/std/examples/welcome.ts"]
```

Script file(sample.ts) is
```typescript
import puppeteer from "https://deno.land/x/puppeteer@9.0.0/mod.ts";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://sample.com");
await page.screenshot({ path: '/root/sample.png' });
await browser.close();
```

Error message is
```bash
$ docker build -t deno .

... building docker image ...
... after successfully built ...

$ docker run --rm -it -v path-to-sample-script-dir:/root deno:latest run -A --uns
table sample.ts
Check file:///root/sample.ts
error: Uncaught (in promise) BadResource: Bad resource ID
    const result = await reader.read(inspectArr);
                   ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async read (deno:runtime/js/12_io.js:97:19)
    at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
    at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
    at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
    at async waitForWSEndpoint (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserRunner.ts:167:20)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserRunner.ts:145:31)
    at async ChromeLauncher.launch (https://deno.land/x/puppeteer@9.0.0/src/deno/Launcher.ts:114:26)
    at async file:///root/sample.ts:4:17
```

**Comment by mt-u** [comment]
Hi @lucacasonato.

I solved this.
I checked the error message by adding `console.log (line);` between lines 167 and 168 of `BrowserRunner.ts` in `deno-puppeteer`.
I found that the cause of the error was that some required packages were not installed.
The packages listed in [troubleshooting](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) of `puppeteer` are not enough, need the following:
```
libdrm2
libxkbcommon0
libxshmfence1
``` 
And one more important thing is written [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku).
If we run as root user inside a Docker container, we need to use `--no-sandbox` mode when launching Puppeteer.
Otherwise error will occur. 

This is my Dockerfile:
```Dockerfile
FROM debian:buster-slim

ENV DENO_VERSION=1.10.1
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    curl \
    ca-certificates \
    unzip \
# ↓ https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
# Since I want to leave the contents of troubleshooting.md as it is, ca-certificates is intentionally duplicated here.
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    wget \
    xdg-utils \
# ↑ https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
# ↓ Added based on the information obtained from by console.log(line) at https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserRunner.ts#L168.
    libdrm2 \
    libxkbcommon0 \
    libxshmfence1 \
# ↑ Added based on the information obtained from by console.log(line) at https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserRunner.ts#L168.
    && curl -fsSL https://github.com/denoland/deno/releases/download/v${DENO_VERSION}/deno-x86_64-unknown-linux-gnu.zip \
    --output deno.zip \
    && unzip deno.zip \
    && rm deno.zip \
    && chmod 755 deno \
    && mv deno /usr/bin/deno \
    && apt-get -qq remove --purge -y \
    curl \
# Do not remove ca-certificates as it is required by puppeteer.
#    ca-certificates \
    unzip \
    && apt-get -y -qq autoremove \
    && apt-get -qq clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd --uid 1993 --user-group deno \
 && mkdir /deno-dir/ \
 && chown deno:deno /deno-dir/

ENV DENO_DIR /deno-dir/

# https://deno.land/x/puppeteer@9.0.0#installation
RUN PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@9.0.0/install.ts

WORKDIR /root/sandbox
ENTRYPOINT ["deno"]
CMD ["run", "https://deno.land/std/examples/welcome.ts"]
```

Thank you.
