### ISSUE TITLE
Installing FF fails with v9

### ISSUE THREAD

**Issue by MarkTiedemann** [lucacasonato/deno-puppeteer#21]
```
C:\> set PUPPETEER_PRODUCT=firefox

C:\> deno run -A --unstable https://deno.land/x/puppeteer@9.0.0/install.ts
Download https://deno.land/x/puppeteer@9.0.0/install.ts
Check https://deno.land/x/puppeteer@9.0.0/install.ts

100.00% 21.1s 83721209/83721209

error: Uncaught (in promise) NotFound: The system cannot find the path specified. (os error 3)
      await Deno.writeFile(ff, content);
      ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at async open (deno:runtime/js/40_files.js:46:17)
    at async Object.writeFile (deno:runtime/js/40_write_file.js:58:18)
    at async JSZip.unzip (https://deno.land/x/puppeteer@9.0.0/vendor/puppeteer-core/vendor/zip/mod.ts:203:7)
    at async extractZip (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserFetcher.ts:473:3)
    at async BrowserFetcher.download (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserFetcher.ts:283:7)
    at async https://deno.land/x/puppeteer@9.0.0/install.ts:34:27

C:\> deno -V
deno 1.9.2
```

Installing Chrome worked just fine.

**Comment by MarkTiedemann** [comment]
I added a `console.log`.

The unzip code is trying to write to `%localappdata%\deno\deno_puppeteer\firefox\win64-90.0a1\firefox\uninstall\helper.exe`.

`%localappdata%\deno\deno_puppeteer\firefox\`  exists. The other subdirectories, `\win64-90.0a1\firefox\uninstall\` don't.

Seems like the code at https://github.com/lucacasonato/deno-puppeteer/blob/9.0.0/vendor/puppeteer-core/vendor/zip/mod.ts#L196-L200 is buggy.
