### ISSUE TITLE
Error: Property 'utime' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by quaos** [lucacasonato/deno-puppeteer#34]
I got this on Deno 1.13.2 and also on latest 1.14.1

OS: MacOS Mojave 10.14.6

```shell
$ deno run --allow-read --allow-net --unstable --config tsconfig.json src/cli.ts
# ...
error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:96:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:111:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:135:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:160:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:183:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.93.0/fs/copy.ts:214:10

$ deno --version
deno 1.13.2 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
$ deno upgrade
# ...
$ deno --version
deno 1.14.1 (release, x86_64-apple-darwin)
v8 9.4.146.15
typescript 4.4.2
```

**Comment by talentlessguy** [comment]
run with `--unstable`

**Comment by quaos** [comment]
> run with `--unstable`

That's strange. I already run with the `--unstable` flag, but still got the error.

```shell
$ deno run --unstable -A --config tsconfig.json src/cli.ts
$ deno run -A --config tsconfig.json --unstable src/cli.ts
```

If I omit `--config tsconfig.json`, the unstable flag seemed to work, but there would be error from missing DOM lib reference.

**Comment by quaos** [comment]
OK, I found the cause. I also needed to add this to `lib` section in `tsconfig.json`:

```json
{
    //...
    "lib": [
      "dom",
      "deno.ns",
      "deno.unstable", // <= add this
      "esnext"
    ]
     //...
}
```

I suppose this issue can be closed now. Thanks!
