### ISSUE TITLE
PermissionDenied:

### ISSUE THREAD

**Issue by ralyodio** [lucacasonato/deno-puppeteer#51]
```
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
    this.proc = Deno.run({
                     ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at opRun (deno:runtime/js/40_process.js:28:17)
    at Object.run (deno:runtime/js/40_process.js:111:17)
    at BrowserRunner.start (https://deno.land/x/puppeteer@14.1.1/src/deno/BrowserRunner.ts:63:22)
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@14.1.1/src/deno/Launcher.ts:108:12)
```

**Comment by jespertheend** [comment]
I had the same issue, removing the directory at `$DENO_DIR/deno_puppeteer/chromium` and reinstalling using `install.ts` fixed it for me.
(run `deno info`, to find out where your $DENO_DIR is)
