### ISSUE TITLE
getting PermissionDenied: 'Deno.makeTempDir' is not allowed in this context

### ISSUE THREAD

**Issue by fcavalcantirj** [lucacasonato/deno-puppeteer#69]
Locally it works fine, running with allow-write on deno run.

when I run on deno, on the logs I get;

`PermissionDenied: 'Deno.makeTempDir' is not allowed in this context.
    at Object.makeTempDir (deno:deploy/js/02_fs.js:193:9)
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:31:49)
    at PuppeteerDeno.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Puppeteer.ts:115:31)
    at crawl (file:///src/index.js:136:35)`

not sure it's a newbie question but how can I run allow-write on deno?

**Comment by tomvorel13** [comment]
Same problem here. Did you get it resolved @fcavalcantirj ?

**Comment by dalezak** [comment]
Having the same issue running `deno-puppeteer` in a Supabase edge function.

**Comment by pencilcheck** [comment]
getting this error as well on deno deploy

**Comment by MrTanoshii** [comment]
Having the same issue because Supabase restricts the file system
See: https://github.com/supabase/edge-runtime/issues/120

The code snippet below is attempting to make a profile for the browser, maybe the solution would be to keep the profile in memory only?
https://github.com/lucacasonato/deno-puppeteer/blob/45b3162585b98ad8d54abeb56f48ecbb17c614eb/src/deno/Launcher.ts#L65-L68

**Comment by tatwater** [comment]
Adding my +1 to the problem others here have encountered with the Supabase edge function file system restriction.

I'm trying to preserve my Browserless.io usage for production by running puppeteer locally in development, but I'm hitting this same error when it tries to make a Chromium instance:

```
[Error] TypeError: Deno.makeTempDir is not a function
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:31:45)
    at PuppeteerDeno.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Puppeteer.ts:115:27)
```

Would be really nice to have an option to keep this in an in-memory buffer while I build out my app!

**Comment by Luchooo** [comment]
Same problem here. Did you get it resolved @tomvorel13 ?

**Comment by Luchooo** [comment]
I'm not sure if this information is useful to you, but from what I understand about Deno deploy, its environment is read-only. Therefore, in the case of using Deno.makeTempDir, Deno's environment requires --allow-write. However, we cannot grant permissions to Deno deploy at the moment. The same issue arises when using page.screenshot(...), as this action also requires --allow-write. If I am mistaken, please let me know. 😀

**Comment by BruceSuperProgramer** [comment]
There's an example in the Supabase repository that utilizes Browserless. I'm currently experimenting with it to evaluate its effectiveness. However, a potential drawback of this approach is the associated cost.

https://github.com/supabase/supabase/pull/10615/files
