### ISSUE TITLE
TypeError: reader is not async iterable  at getReadableStreamAsUint8Array

### ISSUE THREAD

**Issue by mflisikowski** [lucacasonato/deno-puppeteer#73]
**Deno info:**
```shell
🐉 >deno info
DENO_DIR location: /Users/mateuszflisikowski/Library/Caches/deno
Remote modules cache: /Users/mateuszflisikowski/Library/Caches/deno/deps
npm modules cache: /Users/mateuszflisikowski/Library/Caches/deno/npm
Emitted modules cache: /Users/mateuszflisikowski/Library/Caches/deno/gen
Language server registries cache: /Users/mateuszflisikowski/Library/Caches/deno/registries
Origin storage: /Users/mateuszflisikowski/Library/Caches/deno/location_data
```

**TypeError: reader is not async iterable**
```shell
TypeError: reader is not async iterable
    at getReadableStreamAsUint8Array (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/util.js:329:29)
    at Page.pdf (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/Page.js:2606:24)
    at async Server.<anonymous> (file:///home/deno/functions/download-cv/index.ts:21:17)
    at async Server.#respond (https://deno.land/std@0.131.0/http/server.ts:298:18)
```

**Supabase function code, that try to run.**
```javascript
import puppeteer from 'https://deno.land/x/puppeteer@16.2.0/mod.ts';
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

serve(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://mflisikowski.dev/cv', {
    waitUntil: 'networkidle2',
  });

  const pdf = await page.pdf({ format: 'A4' });

  await browser.close();

  return new Response(pdf, {
    headers: {
      'Content-Disposition': `attachment; filename="cv.pdf"`,
      'Content-Type': 'application/pdf',
    },
  });
});
```

**Comment by danilopolani** [comment]
Same here, same as #67   
Probably it's worth waiting for https://github.com/denoland/deno/issues/18913 so we can use Puppeteer from `npm` and have it always updated

**Comment by PhilippS93** [comment]
I also have the same problem using Superbase edge functions and browserless

**Comment by drobles-atdev** [comment]
any updates on solving this issue?

**Comment by julianolm** [comment]
Im also running into this error after `page.pdf` on a supabase edge function. Would love to get updates

**Comment by julianolm** [comment]
Im also running into this error after calling `page.pdf` on a supabase edge function. Would love to get updates

**Comment by vinch** [comment]
Was anyone able to solve this problem? I run into the same issue with Supabase Edge Functions.

**Comment by julianolm** [comment]
@vinch in my use case I could solve the issue by replacing my `puppeteer.launch()` call with a `puppeteer.connect(...)` instead.
For that I had to launch a [browserless io](https://www.browserless.io/) instance and connect puppeteer with it. Check [browserless.io solution here](https://docs.browserless.io/libraries/puppeteer-library/).


Basically my code changed from
```
const browser = await puppeteer.launch();
const page = await browser.newPage();
```
to
```
const browser = await puppeteer.connect({
    browserWSEndpoint: `wss://chrome.browserless.io?token=${Deno.env.get("PUPPETEER_BROWSERLESS_IO_KEY")}`,
});
const page = await browser.newPage();
```

I dont know if that is actually an overkill, but I could solve my problem and the solution was very easy.

ps: Launching browserless instance was super easy (and for my usecase it was free)

**Comment by vinch** [comment]
@julianolm Yeah that's what I did as well but I didn't use Browserless (too expensive for me) but instead ran my own Puppeteer instance on DigitalOcean.

**Comment by julianolm** [comment]
@vinch nailed it! Congrats

**Comment by pasha-bolokhov** [comment]
I was able to use `Puppeteer` directly from `NPM` using the following:

```typescript
import * as Puppeteer from "npm:puppeteer";

const url = "https://example.com";

const BROWSER_PATH = "<path-to-chrome>/chrome";

const browser = await Puppeteer.launch({ headless: true, executablePath: BROWSER_PATH });

const page = await browser.newPage();

await page.goto(url, { waitUntil: "networkidle2" });

const pdf = await page.pdf({ format: "letter" });

await Deno.writeFile("output.pdf", pdf);

await page.screenshot({ path: "output.png" });

await browser.close();
```

It does produce a warning:
```
Warning: Not implemented: ClientRequest.options.createConnection
```
but, despite it, it does complete

Don't know how critical the warning is?
