### ISSUE TITLE
Can't build docker image. It hangs. Package is not usable

### ISSUE THREAD

**Issue by kazeens** [lucacasonato/deno-puppeteer#80]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/31125887/235239151-741fd1e1-5c5f-4004-beda-707c82218481.png">

**Comment by dotellie** [comment]
As poorly written as this bug report is, it is happening for me to - the install script seems to not work on the latest versions of Deno inside a Docker build. It isn't clear to me exactly where the issue is, but if I had to guess I would say some part is not reporting itself as finished properly, causing the downloading process to freeze.

**Comment by kazeens** [comment]
@dotellie please share your detailed experience to gain attention of the maintainers.
It is so sad you can't rely on such an important package in a predictable, normal working fashion

**Comment by jaydenseric** [comment]
With Deno v1.36.4 (and some older versions too), running:

```sh
deno run \
  --allow-env \
  --allow-net \
  --allow-read \
  --allow-write \
  https://deno.land/x/puppeteer@16.2.0/install.ts
```

Results in this error:

```
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.153.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.153.0/node/process.ts:312:7
    at innerInvokeEventListeners (ext:deno_web/02_event.js:750:7)
    at invokeEventListeners (ext:deno_web/02_event.js:797:5)
    at dispatch (ext:deno_web/02_event.js:654:9)
    at dispatchEvent (ext:deno_web/02_event.js:1039:12)
    at [ext:cli/worker.rs:155:38]:1:1
```

**Comment by primeagen-rustaceans** [comment]
Facing the same isue, when importing npm package and running deno script it is working but giving this error core.runMicrotasks();
`error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.165.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.165.0/node/process.ts:314:7
    at innerInvokeEventListeners (ext:deno_web/02_event.js:750:7)
    at invokeEventListeners (ext:deno_web/02_event.js:797:5)
    at dispatch (ext:deno_web/02_event.js:654:9)
    at dispatchEvent (ext:deno_web/02_event.js:1039:12)
    at [ext:cli/worker.rs:155:38]:1:1`
